#!/bin/sh

OUTTYPE=wav

do_convert()
{
	FILE=$1
	if [ -z "${FILE}" ] ; then
		echo "$0 do_convert(): Expected FILE argument" 1>&2
		exit 1
	fi

	case ${TYPE} in
	mono)
		INOPTS="-t raw -r 44100 -w -s -c 1"
	;;
	stereo)
		INOPTS="-t raw -r 44100 -w -s -c 2"
	;;
	*)
		echo "$0 do_convert(): Unexpected TYPE ${TYPE}" 1>&2
		exit 1
	;;
	esac

	sox ${INOPTS} ${FILE} -t ${OUTTYPE} output.${OUTTYPE}
}

##
##	main program
##

ACTION=$1
[ "$1" ] && shift
case ${ACTION} in
mono)		## convert mono@44100 'ekaviel' output
	TYPE=mono do_convert $*
;;
stereo)		## convert mono@44100 'ekaviel' output
	TYPE=stereo do_convert $*
;;
*)
	if [ -n "${ACTION}" -a "${ACTION}" != 'help' ] ; then
		echo "$0: Unrecognised command '${ACTION}'"
	fi
	echo "$0: Usage:"
	grep "^[0-9a-z-]*)" $0 | sed "s/^/	/"
	exit 1
;;
esac
